Grouped statements into fucnctions

diff --git a/kojak b/kojak
--- a/kojak
+++ b/kojak
@@ -21,13 +21,26 @@
 # Switch on Debugging
 set -x
 
-echo -e "\n# Installing packages"
-yum -y install docker git wget unzip net-tools bind bind-utils patch mlocate maven
+# Define logfile
+LOG="/root/install.log"
 
-echo -e "\n# Patching docker"
-[[ -f "/etc/sysconfig/docker.orig" ]]; mv /etc/sysconfig/docker.orig /etc/sysconfig/docker
-cp -p /etc/sysconfig/docker /etc/sysconfig/docker.orig
-cat > /tmp/docker.patch << 'EOF'
+echo -e "########################################################################" >> $LOG
+echo -e "Autom8...Installing Openshift Origin and Fabric8" >> $LOG
+echo -e "########################################################################\n" >> $LOG
+echo -e $(date) >> $LOG
+echo >> $LOG
+
+
+install_packages () {
+    echo -e "\n# Installing packages"
+    yum -y install docker git wget unzip net-tools bind bind-utils patch mlocate maven
+}
+
+install_docker () {
+	echo -e "\n# Patching docker"
+	[[ -f "/etc/sysconfig/docker.orig" ]]; mv /etc/sysconfig/docker.orig /etc/sysconfig/docker
+	cp -p /etc/sysconfig/docker /etc/sysconfig/docker.orig
+	cat > /tmp/docker.patch << 'EOF'
 --- /etc/sysconfig/docker	2015-12-10 17:57:32.000000000 -0500
 +++ /etc/sysconfig/docker	2016-03-31 02:28:46.835000000 -0400
 @@ -21,6 +21,7 @@
@@ -52,27 +65,13 @@ docker pull openshift/origin-docker-builder
 docker pull openshift/origin-deployer
 docker pull openshift/origin-docker-registry
 docker pull openshift/origin-haproxy-router
+}
 
-echo -e "\n# Installing openshift"
-mkdir /opt/openshift-origin-v1.1
-chmod 755 /opt /opt/openshift-origin-v1.1
-cd /opt/openshift-origin-v1.1
-wget https://github.com/openshift/origin/releases/download/v1.1.3/openshift-origin-server-v1.1.3-cffae05-linux-64bit.tar.gz
-tar -zxvf openshift-origin-server-*.tar.gz --strip-components 1
-rm -f openshift-origin-server-*.tar.gz
-
-[[ -f /etc/profile.d/openshift.sh ]]; rm -f /etc/profile.d/openshift.sh
-cat > /etc/profile.d/openshift.sh << 'EOF'
-export OPENSHIFT=/opt/openshift-origin-v1.1
-export PATH=$OPENSHIFT:$PATH
-export KUBECONFIG=$OPENSHIFT/openshift.local.config/master/admin.kubeconfig
-export CURL_CA_BUNDLE=$OPENSHIFT/openshift.local.config/master/ca.crt
-EOF
-
-echo -e "\n# Patching bind"
-[[ -f "/etc/named.conf.orig" ]]; mv /etc/named.conf.orig /etc/named.conf
-cp -p /etc/named.conf /etc/named.conf.orig
-cat > /tmp/bind.patch << 'EOF'
+install_nameserver () {
+    echo -e "\n# Patching bind"
+    [[ -f "/etc/named.conf.orig" ]]; mv /etc/named.conf.orig /etc/named.conf
+    cp -p /etc/named.conf /etc/named.conf.orig
+    cat > /tmp/bind.patch << 'EOF'
 --- /etc/named.conf	2015-06-01 06:43:48.000000000 -0400
 +++ /etc/named.conf	2016-04-18 10:15:51.743000000 -0400
 @@ -8,13 +8,14 @@
@@ -119,10 +118,10 @@ cat > /tmp/bind.patch << 'EOF'
  include "/etc/named.rfc1912.zones";
  include "/etc/named.root.key";
 EOF
-(cd / && patch -p0) < /tmp/bind.patch
-rm -f /tmp/bind.patch
+    (cd / && patch -p0) < /tmp/bind.patch
+    rm -f /tmp/bind.patch
 
-cat > /var/named/122.168.192.zone << 'EOF'
+    cat > /var/named/122.168.192.zone << 'EOF'
 $ORIGIN 122.168.192.in-addr.arpa.
 $TTL 86400
 @       IN      SOA     openshift.example.com.      hostmaster.example.com. (
@@ -139,9 +138,9 @@ $TTL 86400
 101     IN      PTR     master01.example.com.
 101     IN      PTR     node01.example.com.
 EOF
-chmod root:named /var/named/122.168.192.zone
+    chmod root:named /var/named/122.168.192.zone
 
-cat > /var/named/example.com.zone << 'EOF'
+    cat > /var/named/example.com.zone << 'EOF'
 $ORIGIN example.com.
 $TTL 86400
 @               IN      SOA     openshift.example.com.      hostmaster.example.com. (
@@ -160,26 +159,44 @@ openshift           IN      A       192.168.122.101
 master01        IN      A       192.168.122.101
 node01          IN      A       192.168.122.101
 EOF
-chmod root:named /var/named/example.com.zone
-systemctl enable named && systemctl start named
+    chmod root:named /var/named/example.com.zone
+    systemctl enable named && systemctl start named
 
-cat > /etc/resolv.conf << 'EOF'
+    cat > /etc/resolv.conf << 'EOF'
 # Generated by Kojak
 search example.com
 nameserver 127.0.0.1
 EOF
+}
 
-echo -e "\n# Setup openshift"
-chmod 755 /etc/profile.d/openshift.sh
-. /etc/profile.d/openshift.sh
-./openshift start --write-config=openshift.local.config
-chmod +r $OPENSHIFT/openshift.local.config/master/admin.kubeconfig
-chmod +r $OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig
-chmod +r $OPENSHIFT/openshift.local.config/master/openshift-router.kubeconfig
+install_openshift () {
+    echo -e "\n# Installing openshift"
+    mkdir /opt/openshift-origin-v1.1
+    chmod 755 /opt /opt/openshift-origin-v1.1
+    cd /opt/openshift-origin-v1.1
+    wget https://github.com/openshift/origin/releases/download/v1.1.3/openshift-origin-server-v1.1.3-cffae05-linux-64bit.tar.gz
+    tar -zxvf openshift-origin-server-*.tar.gz --strip-components 1
+    rm -f openshift-origin-server-*.tar.gz
 
-echo -e "\n# Patching openshift"
-[[ -f "$OPENSHIFT/openshift.local.config/master/master-config.yaml.orig " ]]; mv $OPENSHIFT/openshift.local.config/master/master-config.yaml.orig $OPENSHIFT/openshift.local.config/master/master-config.yaml
-cp -p $OPENSHIFT/openshift.local.config/master/master-config.yaml $OPENSHIFT/openshift.local.config/master/master-config.yaml.orig 
+    [[ -f /etc/profile.d/openshift.sh ]]; rm -f /etc/profile.d/openshift.sh
+cat > /etc/profile.d/openshift.sh << 'EOF'
+export OPENSHIFT=/opt/openshift-origin-v1.1
+export PATH=$OPENSHIFT:$PATH
+export KUBECONFIG=$OPENSHIFT/openshift.local.config/master/admin.kubeconfig
+export CURL_CA_BUNDLE=$OPENSHIFT/openshift.local.config/master/ca.crt
+EOF
+
+	echo -e "\n# Configure openshift"
+	chmod 755 /etc/profile.d/openshift.sh
+	. /etc/profile.d/openshift.sh
+	./openshift start --write-config=openshift.local.config
+	chmod +r $OPENSHIFT/openshift.local.config/master/admin.kubeconfig
+	chmod +r $OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig
+	chmod +r $OPENSHIFT/openshift.local.config/master/openshift-router.kubeconfig
+
+	echo -e "\n# Patching openshift"
+	[[ -f "$OPENSHIFT/openshift.local.config/master/master-config.yaml.orig " ]]; mv $OPENSHIFT/openshift.local.config/master/master-config.yaml.orig $OPENSHIFT/openshift.local.config/master/master-config.yaml
+	cp -p $OPENSHIFT/openshift.local.config/master/master-config.yaml $OPENSHIFT/openshift.local.config/master/master-config.yaml.orig 
 cat > /tmp/openshift.patch << 'EOF'
 --- /opt/openshift-origin-v1.1/openshift.local.config/master/master-config.yaml	2016-03-31 02:20:22.178000000 -0400
 +++ /opt/openshift-origin-v1.1/openshift.local.config/master/master-config.yaml	2016-03-31 02:28:22.731000000 -0400
@@ -193,49 +210,58 @@ cat > /tmp/openshift.patch << 'EOF'
    limitSecretReferences: false
    managedNames:
 EOF
-(cd / && patch -p0) < /tmp/openshift.patch
-rm -f /tmp/openshift.patch
+    (cd / && patch -p0) < /tmp/openshift.patch
+    rm -f /tmp/openshift.patch
 
-echo -e "\n# Initialising openshift"
-nohup $OPENSHIFT/openshift --cors-allowed-origins='.*' start &
+    echo -e "\n# Initialising openshift"
+    nohup $OPENSHIFT/openshift --cors-allowed-origins='.*' start &
 
-while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8443"; do echo -e "# Retrying...please be patient" && sleep 12 ; done
+    while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8443"; do echo -e "# Retrying...please be patient" && sleep 12 ; done
 
-echo -e "\n# Create service accounts for registry and router"
-oc login -u system:admin -n default
-oc project default
-echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"registry"}}' | oc create -f -
-echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router"}}' | oc create -f -
-wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
-chmod +x jq-linux64
-oc get scc privileged -o json | ./jq-linux64 '.users |= .+ ["system:serviceaccount:default:registry"]' | oc replace scc -f -
-oc get scc privileged -o json | ./jq-linux64 '.users |= .+ ["system:serviceaccount:default:router"]' | oc replace scc -f -
-oadm policy add-cluster-role-to-user cluster-admin admin
+	echo -e "\n# Create service accounts for registry and router"
+	oc login -u system:admin -n default
+	oc project default
+	echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"registry"}}' | oc create -f -
+	echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router"}}' | oc create -f -
+	wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
+	chmod +x jq-linux64
+	oc get scc privileged -o json | ./jq-linux64 '.users |= .+ ["system:serviceaccount:default:registry"]' | oc replace scc -f -
+	oc get scc privileged -o json | ./jq-linux64 '.users |= .+ ["system:serviceaccount:default:router"]' | oc replace scc -f -
+	oadm policy add-cluster-role-to-user cluster-admin admin
 
-echo -e "\n# Create docker registry"
-mkdir /opt/openshift-registry
-chown ${USER}.${USER} /opt/openshift-registry
-oadm registry --credentials=$OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig --service-account=registry --mount-host=/opt/openshift-registry
-echo -e "\n# Create router"
-oadm router router --replicas=1 --credentials=$OPENSHIFT/openshift.local.config/master/openshift-router.kubeconfig --service-account=router
-curl -sk https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json | oc create -n openshift -f -
+	echo -e "\n# Create docker registry"
+	mkdir /opt/openshift-registry
+	chown ${USER}.${USER} /opt/openshift-registry
+	oadm registry --credentials=$OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig --service-account=registry --mount-host=/opt/openshift-registry
+	echo -e "\n# Create router"
+	oadm router router --replicas=1 --credentials=$OPENSHIFT/openshift.local.config/master/openshift-router.kubeconfig --service-account=router
+	curl -sk https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json | oc create -n openshift -f -
+}
 
-echo -e "\n# Downloading gofabric8"
-cd /opt
-wget https://github.com/fabric8io/gofabric8/releases/download/v0.4.9/gofabric8-0.4.9-linux-amd64.tar.gz
-mkdir gofabric8
-tar zxfv gofabric8-0.4.9-linux-amd64.tar.gz -C gofabric8/
+install_fabric8 () {
+	echo -e "\n# Downloading gofabric8"
+	cd /opt
+	wget https://github.com/fabric8io/gofabric8/releases/download/v0.4.9/gofabric8-0.4.9-linux-amd64.tar.gz
+	mkdir gofabric8
+	tar zxfv gofabric8-0.4.9-linux-amd64.tar.gz -C gofabric8/
 
-echo -e "\n# Downloading fabric8 templates"
-curl -o fabric8.zip http://repo1.maven.org/maven2/io/fabric8/devops/distro/distro/2.2.95/distro-2.2.95-templates.zip
-unzip -d fabric8 fabric8.zip
+	echo -e "\n# Downloading fabric8 templates"
+	curl -o fabric8.zip http://repo1.maven.org/maven2/io/fabric8/devops/distro/distro/2.2.95/distro-2.2.95-templates.zip
+	unzip -d fabric8 fabric8.zip
 
-echo -e "\n# Installaing fabric8"
-/opt/gofabric8/gofabric8 deploy --namespace="default" --domain example.com --yes 
-/opt/gofabric8/gofabric8 secrets --yes
+	echo -e "\n# Installaing fabric8"
+	/opt/gofabric8/gofabric8 deploy --namespace="default" --domain example.com --yes 
+	/opt/gofabric8/gofabric8 secrets --yes
 
-echo -e "\n# Configure namespace"
-oc get oauthclient fabric8
-oc process -v DOMAIN=example.com -f /opt/fabric8/main/cd-pipeline-2.2.95.json | oc create -f -
-/opt/gofabric8/gofabric8 validate --namespace="default"
+	echo -e "\n# Configure namespace"
+	oc get oauthclient fabric8
+	oc process -v DOMAIN=example.com -f /opt/fabric8/main/cd-pipeline-2.2.95.json | oc create -f -
+	/opt/gofabric8/gofabric8 validate --namespace="default"
+}
+
+install_packages
+install_docker
+install_nameserver
+install_openshift
+install_fabric8
 
